### ISSUE TITLE
Missing origin in base.yaml

### ISSUE THREAD

**Issue by mojivalipour** [felixludos/learn_rep#1]
It seems that your current code still needs origin, but you removed that origin.yaml at some points in your code. I even download an origin.yaml from your past commits but then there was an error for missing train config. How we can run your code successfully?

**Comment by felixludos** [comment]
That error is familiar (`origin.yaml` is added automatically through `omni-learn`). It means one of the dependencies is out of date (either `omni-fig` or `omni-learn`). Those dependencies should now be updated, as follows:
`omnibelt` >= 0.5.1
`omnifig` >= 0.6.2
`omnilearn` >= 0.5.14

Also, I finally setup the CI builds, which should help make sure the demo can be run without errors.
