### ISSUE TITLE
Can't find factor_responses

### ISSUE THREAD

**Issue by rafaela-amorim** [felixludos/learn_rep#4]
Hi Felix, I am trying to run some of your notebooks and I'm having trouble with the codes imported from src. I couldn't find factor_responses anywhere in this repository. Perhaps the name has changed, or it doesn't exist anymore?

**Comment by felixludos** [comment]
Yeah, sorry - all of the latent response related material has been moved to its own repo: [felixludos/latent-responses](https://github.com/felixludos/latent-responses) (which is currently quite a bit more cleaned up than this one).
If you just want to get the notebooks running, I suggest removing anything referring to latent responses for now (as I'm still semi-actively using these notebooks myself). Or if you have something specific you are looking for, I might also be able to prioritize that as I gradually clean up things up.

**Comment by rafaela-amorim** [comment]
thank you very much, for now I actually needed factor_responses, because I'm reading _Structured Representation Learning using Structural Autoencoders and Hybridization_ and I wanted to follow the methodology described on it. I was looking it up in FactorDataset class but couldn't find something similar to latent factor response. Are you currently working on it or maybe I just couldn't find it?

**Comment by felixludos** [comment]
The structural autoencoders (SAEs) are separate from the latent responses. If you are just looking for implementations of SAEs, then I'd suggest just removing any code that refers to latent responses (they are just for a special kind of analysis anyway).
